[webservers]
web1 ansible_host=158.158.0.234
web2 ansible_host=135.116.17.241

[dbservers]
db1 ansible_host=74.248.184.208

[all:vars]
ansible_user=azureuser
ansible_ssh_private_key_file=~/.ssh/id_ed25519