apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-monitoring-kube-prometheus-alertmanager
  namespace: monitoring
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m
    route:
      group_by: ['namespace']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'null'
      routes:
      - matchers:
        - alertname="PodRestart"
        receiver: 'send-email'
        repeat_interval: 5m
      - matchers:
        - alertname="HighCpuUsage"
        receiver: 'send-email'
      - matchers:
        - alertname="Watchdog"
        receiver: 'null'
    receivers:
    - name: 'null'
    - name: 'send-email'
      email_configs:
      - to: mdhow0007@gmail.com
        from: mdasadulhowlader1998bd@gmail.com
        send_resolved: false
        smarthost: smtp.gmail.com:587
        auth_username: mdasadulhowlader1998bd@gmail.com
        auth_identity: mdasadulhowlader1998bd@gmail.com
        auth_password: "gfqq rmbn zdsg lnia"
    inhibit_rules:
    - source_matchers:
      - severity="critical"
      target_matchers:
      - severity=~"warning|info"
      equal: [namespace, alertname]
